# Generated by Django 2.2.6 on 2020-12-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldmain', '0004_auto_20201217_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note_author',
        ),
    ]
