# Generated by Django 2.2.6 on 2020-12-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goldmain', '0005_remove_notes_note_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='day',
            new_name='created',
        ),
        migrations.AddField(
            model_name='notes',
            name='note_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='gold_forecast',
            field=models.FloatField(),
        ),
    ]
