# Generated by Django 2.2.6 on 2020-12-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goldmain', '0006_auto_20201218_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='verification_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Purchase Date(yyyy-mm-dd)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
