# Generated by Django 2.2.6 on 2020-12-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldmain', '0007_auto_20201218_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_result', models.BooleanField()),
                ('accuracy', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='gold_forecast',
            field=models.FloatField(verbose_name='Gold-price Forecast'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='verification_date',
            field=models.DateField(blank=True, verbose_name='Expected Date(yyyy-mm-dd)'),
        ),
        migrations.DeleteModel(
            name='History_Forecast',
        ),
        migrations.AddField(
            model_name='forecastverification',
            name='forecast_to_verification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goldmain.Forecast'),
        ),
    ]
